### PR TITLE
fix(android): fixed Android environment detection in CLI info

### LINKED ISSUE #14374: `ti info` not showing all Android information
### I have searched and made sure there are no existing issues for the issue I am filing

- [x] I have searched the existing issues

### Description

Currently running `ti info -t android` won't show any emulator/sdk/etc. output:
```
$ ti info -t android
Titanium Command-Line Interface v8.1.2 SDK v13.1.0.GA
Copyright TiDev, Inc. 4/7/2022-Present. All Rights Reserved.

Please star us on GitHub! https://github.com/tidev/titanium-cli
and https://github.com/tidev/titanium-sdk

Want to help? https://tidev.io/donate or https://tidev.io/contribute

Issues
  No issues detected! Your development environment should be working perfectly!
```

The old `ti info -t android --sdk 13.0.1.GA` will show the logs.
Building apps works fine though!

### Expected Behavior

show logs

### Actual behavior

not showing anything

### Reproducible sample

`ti info -t android`

### Steps to reproduce

run `ti info -t android`

### Platform

Android, CLI

### SDK version you are using

13.1.0

### Alloy version you are using

3.0.0

### PR DESCRIPTION
**Pull request by hbugdoll**
Fixes #14374.

**Description:**

- ChatGPT says: `android/cli/lib/detect.js` has no `default export`, so `mod` is undefined in:
https://github.com/tidev/titanium-sdk/blob/53dcb9b7de731a8b44b31b21494682fdbd9a0a00/android/cli/lib/info.js#L21
- changed the import from `{ default: mod }` to `mod`
- `ti info -t android` works fine again

### CODE REVIEW

File: android/cli/lib/info.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export function detect(types, config, next) {
 		return dir !== '/' && scan(dir);
 	}(__dirname)));
 
-	import('./detect.js').then(({ default: mod }) => {
+	import('./detect.js').then((mod) => {
```
Comment (cb1kenobi) [inline android/cli/lib/info.js:21]: Oh, I get it now. `detect.js` doesn't have a default export. Ugh. Nice catch!

**Review by cb1kenobi — APPROVED** [review]

File: android/cli/lib/info.js (hunk 1 above)
Comment (hbugdoll) [reply android/cli/lib/info.js:21]: Thank you to AI.
