### PR TITLE
fix(android): lower build gradle

### LINKED ISSUE #13570: Android: Modules build with 11.1.0.GA not working in apps
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Gradle tools in master were updated to 7.2.2. Building a module with it breaks apps:

```
[ERROR] E/ga.testfirebase: No implementation found for void com.williamrijksen.onesignal.TiModuleBootstrap.nativeBootstrap() (tried Java_com_williamrijksen_onesignal_TiModuleBootstrap_nativeBootstrap and Java_com_williamrijksen_onesignal_TiModuleBootstrap_nativeBootstrap__)
```

Lowering it back to 7.0.4 again makes it work again.

**Fix:**
11.1.X: https://github.com/tidev/titanium_mobile/pull/13572
Master: https://github.com/tidev/titanium_mobile/pull/13571

### PR DESCRIPTION
**Pull request by m1ga**
fixes #13570 

**Test** 
* build a module for Android
* include the module in an app

currently SDK and apps have a different build.gradle since I can't update the SDKs version. It looks like modules don't like that :smile:

### CODE REVIEW

File: android/cli/commands/_build.js [hunk 1]
```diff
@@ -2184,6 +2184,7 @@ AndroidBuilder.prototype.generateRootProjectFiles = async function generateRootP
 	const gradleProperties = await gradlew.fetchDefaultGradleProperties();
 	gradleProperties.push({ key: 'android.useAndroidX', value: 'true' });
 	gradleProperties.push({ key: 'android.enableJetifier', value: 'true' });
+	gradleProperties.push({ key: 'android.suppressUnsupportedCompileSdk', value: '33' });
```
Comment (hansemannn) [inline android/cli/commands/_build.js:2187]: This line was not changed in the 11_1_X branch, is it necessary?

Comment (m1ga) [reply android/cli/commands/_build.js:2187]: only to target SDK 33. Otherwise it will show a warning all the time. 11_1_X is not targeting 33 so I didn't include it there
