### PR TITLE
fix(android): correct ScrollView.contentOffset units

### LINKED ISSUE #12608: Android. ScrollView. Inconsistent units in `contentOffset`
`Ti.UI.ScrollView` on Android returns value for `contentOffset` in pixels and dp.

### To Reproduce
<details>
  <summary>Sample app</summary>
 
```javascript
const win = Ti.UI.createWindow({
  backgroundColor: 'white',
  layout: 'vertical',
});

const scroll = Ti.UI.createScrollView({
  scrollType: 'horizontal',
  backgroundColor: 'black',
  width: Ti.UI.FILL,
  height: '50%',
  center: {
    y: '50%'
  }
});

const longView = Ti.UI.createView({
  width: 2000,
  height: Ti.UI.FILL,
  backgroundGradient: {
    type: 'linear',
    startPoint: {
      x: '0%',
      y: '50%'
    },
    endPoint: {
      x: '100%',
      y: '50%'
    },
    colors: [
      {color: 'red', offset: 0},
      {color: 'green', offset: 0.5},
      {color: 'blue', offset: 1}
    ]
  }
});

setInterval(() => {
  console.log('contentOffset.x:', scroll.contentOffset.x);
}, 300);

const inc = Ti.UI.createButton({
  title: '+100'
});
const dec = Ti.UI.createButton({
  title: '-100'
});

inc.addEventListener('click', function() {
  let { x, y } = scroll.contentOffset;
  x += 100;
  // I know it's possible to overscroll here
  // It doesn't matter for this case
  scroll.contentOffset = {x, y };
})
dec.addEventListener('click', function() {
  let { x, y } = scroll.contentOffset;
  x -= 100;
  if (x < 0) {
    x = 0;
  }
  scroll.contentOffset = {x, y };
})

win.add(inc);
win.add(dec);

scroll.add(longView);
win.add(scroll);
win.open();


  ```
  
</details>

1. Put code above in the `app.js`, build the app, observe console output
2. Click `+100` button five times
3. Notice `contentOffset.x: 500` in the output (value in `dp`)
4. Drag scroll view slightly to the right, so the offset should decrease
5. Notice `contentOffset.x: <VALUE>` in the output increased (value in `pixels`)

P.S. Default app template has `<property name="ti.ui.defaultunit" type="string">dp</property>` in it.

### Expected behavior
`contentOffset` property of `Ti.UI.ScrollView` must contain values in consistent units

### Environment
Titanium SDK version: 9.3.2.GA, 10.1.0 (`master`)

### PR DESCRIPTION
**Pull request by garymathews**
- Correctly handle `ScrollView.contentOffset` units

##### TEST CASE
- Scroll part way into _green_ and click _red_, this should scroll back to the top
- Scroll part way into _blue_ and click _green_, this should scroll to _green_
- Clicking _blue_ should scroll `100dp` into _red_
```JS
const win = Ti.UI.createWindow();
const scrollView = Ti.UI.createScrollView({
    layout: 'vertical',
    backgroundColor: 'white',
    width: Ti.UI.FILL,
    height: Ti.UI.FILL
});
const view_a = Ti.UI.createView({
    backgroundColor: 'red',
    width: '100%',
    height: '100%'
});
const view_b = Ti.UI.createView({
    backgroundColor: 'green',
    width: '100%',
    height: '100%'
});
const view_c = Ti.UI.createView({
    backgroundColor: 'blue',
    width: '100%',
    height: '100%'
});

view_a.addEventListener('click', e => {
    console.log(`previous contentOffset: ${JSON.stringify(scrollView.contentOffset)}`);
    scrollView.contentOffset = {
        x: 0,
        y: 0
    };
    console.log(`new contentOffset: ${JSON.stringify(scrollView.contentOffset)}`);
});

view_b.addEventListener('click', e => {
    console.log(`previous contentOffset: ${JSON.stringify(scrollView.contentOffset)}`);
    scrollView.contentOffset = {
        x: 0,
        y: view_a.rect.height
    };
    console.log(`new contentOffset: ${JSON.stringify(scrollView.contentOffset)}`);
});

view_c.addEventListener('click', e => {
    console.log(`previous contentOffset: ${JSON.stringify(scrollView.contentOffset)}`);
    scrollView.contentOffset = {
        x: 0,
        y: '100dp'
    };
    console.log(`new contentOffset: ${JSON.stringify(scrollView.contentOffset)}`);
});

scrollView.add([
    view_a,
    view_b,
    view_c
]);

win.add(scrollView);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28397)
https://github.com/appcelerator/titanium_mobile/issues/12608

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

File: android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java [hunk 1]
```diff
@@ -713,7 +734,7 @@ public void propertyChanged(String key, Object oldValue, Object newValue, KrollP
 
 		if (key.equals(TiC.PROPERTY_CONTENT_OFFSET)) {
 			setContentOffset(newValue);
```
Comment (drauggres) [inline android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java:736]: Actually, there is no need to call it here. We will call `setContentOffset(int x, int y)` later from `onScrollChanged` which is triggered by the `scrollTo` on the next line.

**Comment by lokeshchdhry** [comment]
FR Passed.
