### PR TITLE
fix(android): build module with example app

### LINKED ISSUE #14132: Android: build module with example app broken
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When building an Android module with `ti build -p android` to execute the example app it currently fails because of https://github.com/tidev/titanium-sdk/pull/14112

The change was in:
https://github.com/tidev/titanium-sdk/blob/12_5_X/android/cli/commands/_buildModule.js#L877

which "works" but `tiSdkVersion` is just `12.5.1` and it will fail because it wants `12.5.1.GA`.

I didn't notice it before since I had `12.5.0` or `12.6.0` installed.

Is there a way to get the GA release or should I add if it is missing?

### Reproducible sample

create a module and build it with `ti build -p android`. Make sure you don't have `12.5.1` just the `12.5.1.GA` version

### Platform

Android

### SDK version you are using

12.5.1.GA

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by m1ga**
fixes: https://github.com/tidev/titanium-sdk/issues/14132

more info in the issue

### CODE REVIEW

File: android/cli/commands/_buildModule.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ AndroidModuleBuilder.prototype.migrate = async function migrate() {
 	const manifestModuleAPIVersion = this.manifest.apiversion;
 	const manifestTemplateFile = path.join(this.platformPath, 'templates', 'module', 'default', 'template', 'android', 'manifest.ejs');
 	let newVersion = semver.inc(this.manifest.version, 'major');
-	this.tiSdkVersion = cliSDKVersion;
+	this.tiSdkVersion = cliSDKVersion.includes('.GA') ? cliSDKVersion : cliSDKVersion + '.GA';
```
Comment (cb1kenobi) [inline android/cli/commands/_buildModule.js:61]: The Titanium CLI stores the SDK name in the `cli.sdk`:

```
{
  name: '12.4.0.GA',
  manifest: {
    name: '12.4.0.GA',
    version: '12.4.0',
    moduleAPIVersion: { iphone: '2', android: '4' },
    timestamp: '7/17/2024 18:43',
    githash: 'a5451fc00d',
    platforms: [ 'android' ]
  },
  path: 'C:\\ProgramData\\Titanium\\mobilesdk\\win32\\12.4.0.GA',
  platforms: {
    android: {
      path: 'C:\\ProgramData\\Titanium\\mobilesdk\\win32\\12.4.0.GA\\android'
    }
  },
  type: 'ga',
  version: '12.4.0'
}
```

So we can do:

```suggestion
	this.tiSdkVersion = this.cli.sdk.name;
```

**Review by cb1kenobi — CHANGES_REQUESTED** [review]

**Review by hansemannn — APPROVED** [review]
