### PR TITLE
fix(ios): optimize ListView continuousUpdate

### LINKED ISSUE #13537: iOS: optimize continuousUpdate
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The new `continuousUpdate` works fine! Already changed some marker events to use `scrolling` now! Much more reliable. 

One think we could optimize is: only call the event on iOS when the item or section changed. Thats how Android is doing it but I'm not able to add that to iOS too 😊  So it should only fire once a new item or section is at the top. 

It should be something like this:

```
int lastVisibleItem = -1;
int lastVisibleSection = -1;

if (lastVisibleItem != NUMINTEGER([indexPath row]) || lastVisibleSection != NUMINTEGER([indexPath section])) {
            [self.proxy fireEvent:@"scrolling" withObject:eventArgs propagate:NO];
            lastVisibleItem = NUMINTEGER([indexPath row]);
            lastVisibleSection = NUMINTEGER([indexPath section]);
}
```

at https://github.com/tidev/titanium_mobile/blob/340abdd08d422d0b7b2dca5f5dda797c20549582/iphone/Classes/TiUIListView.m#L1938

Guess its a quick fix by one of the iOS devs 😉 

Firing the event with the same values won't help so it should only fire when something happened during scrolling. And it would be full Android parity! If you have bigger ListItems it will reduce the event callbacks

### Platforms

iOS

### PR DESCRIPTION
**Pull request by m1ga**
Fixes https://github.com/tidev/titanium_mobile/issues/13537

Optimization for the old PR: https://github.com/tidev/titanium_mobile/pull/13095
It will fire less events, only when the item really changes. Android works like this already. Currently iOS will fire `scrolling` even if the same item is still the top item when you scroll. 

**Workaround** is very simple inside JS but not sending the same event multiple times would be better

```js
var toggle = true;
var sections = [];
const win = Ti.UI.createWindow();
const btn = Ti.UI.createButton({
	title: "change",
	bottom: 20
});
const lbl = Ti.UI.createLabel({
	top: 10,
	right: 10,
	width: Ti.UI.SIZE,
	height: Ti.UI.SIZE
})
const listView = Ti.UI.createListView({
	height: Ti.UI.FILL,
	width: Ti.UI.FILL,
	continuousUpdate: true
});

btn.addEventListener("click", function() {
	toggle = !toggle;
	listView.continuousUpdate = toggle
	console.log(listView.continuousUpdate);
})

for (var s = 0; s < 5; s++) {
	var section = Ti.UI.createListSection({
		headerTitle: 'Section ' + s
	});
	var set = [];
	for (var i = 0; i < 20; ++i) {
		set.push({
			properties: {
				title: 'Item 0 ' + i
			}
		})
	}
	section.setItems(set);
	sections.push(section);
}

listView.sections = sections;
win.add([listView, btn, lbl]);

listView.addEventListener("scrolling", function(e) {
	lbl.text = "Item: " + e.firstVisibleItemIndex + " section:" + e.firstVisibleSectionIndex;
	console.log("Item", e.firstVisibleItemIndex, e.firstVisibleSectionIndex);
})
win.open();
```

### CODE REVIEW

File: iphone/Classes/TiUIListView.m [hunk 1]
```diff
@@ -1969,6 +1971,14 @@ - (void)scrollViewDidScroll:(UIScrollView *)scrollView
           [eventArgs setValue:NUMINTEGER([indexPath section]) forKey:@"firstVisibleSectionIndex"];
           [eventArgs setValue:section forKey:@"firstVisibleSection"];
           [eventArgs setValue:[section itemAtIndex:[indexPath row]] forKey:@"firstVisibleItem"];
+
+          if (lastVisibleItem == [indexPath row] && lastVisibleSection == [indexPath section]) {
+            // skip event - still the same item at the top
+          } else {
+            [self.proxy fireEvent:@"scrolling" withObject:eventArgs propagate:NO];
```
Comment (hansemannn) [inline iphone/Classes/TiUIListView.m:1978]: Simplify the if-statement to `lastVisibleItem != [indexPath row] || lastVisibleSection != [indexPath section]`?
