### PR TITLE
fix(ios): include LaunchLogos again

### LINKED ISSUE #14354: iOS: LaunchLogos are not working
### I have searched and made sure there are no existing issues for the issue I am filing

- [x] I have searched the existing issues

### Description

A recent report on Slack is saying that the LaunchLogos are not working. Testing it with a default app project I can see that it won't use these icons:
https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html#customising-the-image

I did a quick log here: https://github.com/tidev/titanium-sdk/blob/main/iphone/cli/commands/_build.js#L5291 and saw that the LaunchLogos are not inside the object.

The regex here: https://github.com/tidev/titanium-sdk/blob/main/cli/lib/gather.js#L9 is checked here: https://github.com/tidev/titanium-sdk/blob/main/cli/lib/gather.js#L298 but `info.name` does not include the file ending, just the name. That's why it is not matching the icons.

### Expected Behavior

Icons should be used

### Actual behavior

will use the DefaultIcon to generate images

### Reproducible sample

* create a blank app
* put the following LaunchLogos into Resources/iphone/
[LaunchLogo.zip](https://github.com/user-attachments/files/23939424/LaunchLogo.zip) 

### Steps to reproduce

build the app

### Platform

iOS

### SDK version you are using

13.0.1

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by m1ga**
fixes #14354 

`info.name` only includes the file name without the ending. `relPath` has the full filename including ending which is required by the regex.

**Test:**

* create a blank app
* put the following LaunchLogos into Resources/iphone/
[LaunchLogo.zip](https://github.com/user-attachments/files/23939424/LaunchLogo.zip) 
* build the app and check for the orange launch logo instead of the default Ti logo
* if it is too fast: remove the tabgroup.open() from the test app

### CODE REVIEW

**Comment by cb1kenobi** [comment]
I think the problem is iOS doesn't supports jpgs in launch storyboards. You're welcome to test it and if I (and the Internet) are wrong, then we can add support for them in Titanium. :)

**Comment by hbugdoll** [comment]
@cb1kenobi JPG launch logos in launch storyboards work fine (a [named image asset](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/ImageSetType.html) is used).

The restriction to PNG was for deprecated [launch images](https://developer.apple.com/documentation/bundleresources/information-property-list/uilaunchimages), see [Launch Image Type](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/LaunchImageType.html).

**Comment by m1ga** [comment]
I'll close this. As @hbugdoll mentioned in the issue: the real LaunchlLogos are copied over in a later method. And that will also look better in the xcode project as the "LaunchLogo" thumbnail is set and the :warning: icons are gone
Bildschirmfoto 2025-12-05 um 09 40 30

**Comment by hbugdoll** [comment]
> I'll close this. As @hbugdoll mentioned in the issue: the real LaunchlLogos are copied over in a later method.

But that's just luck.
Your PR is needed for `launchLogos` to work as intended in `_build.js`.

To vanish the :warning: simply add my suggested changes at https://github.com/tidev/titanium-sdk/issues/14354#issuecomment-3617362039 to this PR,
which fixes errors in the generated `build/iphone/Assets.xcassets/LaunchLogo.imageset/Contents.json`.

File: cli/lib/gather.js [hunk 1]
```diff
@@ -295,7 +295,7 @@ export class Categorizer {
 				} else if (this.platform === 'ios') {
 					// if the image is the LaunchLogo.png, then let that pass so we can use it
 					// in the LaunchScreen.storyboard
-					const m = info.name.match(LAUNCH_LOGO_REGEXP);
+					const m = relPath.match(LAUNCH_LOGO_REGEXP);
 					if (m) {
 						info.scale = m[1];
 						info.device = m[2];
```
Comment (hbugdoll) [inline cli/lib/gather.js]: Remove `~` in line 301, so e.g. `~ipad` become `ipad`.
```
info.device = m[2].replace('~', '');
```

**Comment by hbugdoll** [comment]
You've already pushed it, but after a night's sleep, I'm wondering whether it might be better for **code readability** not to change `_build.js` in line 6180.
`gather.js` line 300 would then become something like `info.scale = m[1]?.replace(/@|x/g, '');`

**Pros:** Consistency &ndash; in all `lookup` "tables", `scale` is numerical and the `x` is appended afterwards.
**Cons:** The `x` would first be removed and then added again.

What do you think @miga @cb1kenobi ?

**Comment by m1ga** [comment]
I like that better :+1: That way we only do the change in one file and the rest works as before

**Comment by hbugdoll** [comment]
`build/iphone/Assets.xcassets/LaunchLogo.imageset/Contents.json` looks fine now 👍 

```
{
  "images": [
    {
      "idiom": "ipad",
      "filename": "LaunchLogo@2x~ipad.png",
      "scale": "2x"
    },
    {
      "idiom": "iphone",
      "filename": "LaunchLogo@2x~iphone.png",
      "scale": "2x"
    },
    {
      "idiom": "iphone",
      "filename": "LaunchLogo@3x~iphone.png",
      "scale": "3x"
    },
    {
      "idiom": "ipad",
      "filename": "LaunchLogo~ipad.png",
      "scale": "1x"
    },
    {
      "idiom": "iphone",
      "filename": "LaunchLogo~iphone.png",
      "scale": "1x"
    }
  ],
  "info": {
    "version": 1,
    "author": "xcode"
  }
}
```

**Comment by cb1kenobi** [comment]
@hbugdoll sounds good! Which PR has the fix? This one? I can't test it (yet), but I can review it.

**Comment by hbugdoll** [comment]
> @hbugdoll sounds good! Which PR has the fix? This one? I can't test it (yet), but I can review it.

Yeah, this one.
Together, it only ended up with these 3 lines of code: https://github.com/tidev/titanium-sdk/pull/14355/files

**Review by cb1kenobi — APPROVED** [review]
Looks good!
