### PR TITLE
fix(android): fix tintColor and activeTintColor in a TabbedBar

### LINKED ISSUE #14087: Android: TabbedBar icon doesn't tint like the label.
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I'm using BarItemType for icons in a tabbed bar but unlike the label, it doesn't tint/color to any colour. I've tried a few properties but nothing will change it, it keeps to the default blue color.

### Expected Behavior

For the icon to change to whatever colour i set like it does with labels

### Actual behavior

Stays the default material/android blue.

### Reproducible sample

In XML
<TabbedBar id='tabbedBar' class='tabbedBar' onClick='onTabClick'>
	<BarItemTypes>
		<BarItemType id='tab1' image=''/> 
	</BarItemTypes>
</TabbedBar>

In TSS

".tabbedBar" : {
	height : 50,
	width : Ti.UI.FILL,
	tintColor : '#D4AF37',
	selectedTextColor : '#000000',
	backgroundFocusedColor : '#D4AF37',
	selectedBackgroundColor : '#D4AF37',
	bottom : 5
}

### Steps to reproduce

use the code above and observe the active colour being blue

### Platform

_No response_

### SDK version you are using

12.2.1.GA

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by m1ga**
fixes https://github.com/tidev/titanium-sdk/issues/14087

`tintColor` and `activeTintColor` are not working in a TabbedBar:

```js
var win = Ti.UI.createWindow();
var bb1 = Ti.UI.createTabbedBar({
	top: 10,
  	width : Ti.UI.FILL,
  	labels: [{label:"test", image:"appicon.png"}, {label:"test", image:"appicon.png"}, {label:"test", image:"appicon.png"}]
});
win.add(bb1);


var bb2 = Ti.UI.createTabbedBar({
  	width : Ti.UI.FILL,
  	tintColor : '#D4AF37',
  	activeTintColor : '#f00',
  	labels: [{label:"test", image:"appicon.png"}, {label:"test", image:"appicon.png"}, {label:"test", image:"appicon.png"}]
});
win.add(bb2);

var btn = Ti.UI.createButton({title:"select", bottom: 10});
win.add(btn);
btn.addEventListener("click", function(e){
	bb1.index = 1;
	bb2.index = 1;
})
win.open();
```

**12.4.0:**
Screenshot_20240723-181235

**After PR:**
Screenshot_20240723-181527

### CODE REVIEW

File: android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java [hunk 1]
```diff
@@ -133,9 +134,14 @@ protected void onLayout(boolean changed, int l, int t, int r, int b)
 				// no selected color specified but a text color -> use that
 				selectedTextColor = textColor;
 			}
-
 			this.tabLayout.setTabTextColors(textColor, selectedTextColor);
 		}
+		if (this.tabLayout.getTabAt(0).getIcon() != null
```
Comment (hansemannn) [inline android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java:139]: Could this crash if no tab is set at all (e.g. `this.tabLayout.getTabAt(0)` being `null`)?

File: android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java [hunk 2]
```diff
@@ -261,6 +267,11 @@ private void addItem(Object value)
 					if (value instanceof Drawable) {
 						tab.setIcon(((Drawable) value));
 						TiUITabLayoutTabGroup.scaleIconToFit(tab);
+
+						if (tab.getIcon() != null && proxy.hasPropertyAndNotNull(TiC.PROPERTY_TINT_COLOR)) {
+							tab.getIcon().setColorFilter(TiConvert.toColor(proxy.getProperty(TiC.PROPERTY_TINT_COLOR),
+								TiApplication.getAppCurrentActivity()), PorterDuff.Mode.SRC_IN);
```
Comment (hansemannn) [inline android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java:273]: The logic repeats at several places, please move this to a reusable util

**Review by hansemannn — CHANGES_REQUESTED** [review]
