### PR TITLE
fix(android): fix Android FAB tintColor

### LINKED ISSUE #13971: Android: FAB tintColor
Reminder for myself: check FAB tintColor

### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Check FAB tintColor

### Platform

Android

### SDK version you are using

12.2.1

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by m1ga**
Fixes #13971 

Currently `tintColor` is not tinting the icon. This PR will fix that

**Test:**

```js
const win = Ti.UI.createWindow();
const fab = Ti.UI.Android.createFloatingActionButton({
	bottom: 10,
	right: 10,
	tintColor: "blue",
	image: "/appicon.png"
});
win.add(fab);

setTimeout(function() {
	fab.tintColor = "red";
}, 2000)
win.open();
```

* icon will be blue
* after 2 sec it will be red

### CODE REVIEW

File: android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIFloatingActionButton.java [hunk 1]
```diff
@@ -54,6 +55,9 @@ public void processProperties(KrollDict d)
 		if (d.containsKey("maxImageSize")) {
 			setMaxImageSize(TiConvert.toInt(d.get("maxImageSize")));
 		}
+		if (d.containsKey(TiC.PROPERTY_TINT_COLOR)) {
+			setTintColor(d.getString("tintColor"));
```
Comment (hansemannn) [inline android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIFloatingActionButton.java:59]: Can you add docs for the new property please?

**Review by hansemannn — CHANGES_REQUESTED** [review]

File: android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIFloatingActionButton.java (hunk 1 above)
Comment (m1ga) [reply android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIFloatingActionButton.java:59]: ups, sorry. I only looked at the docs and saw it but it was under "excludes" :smile:

**Review by hansemannn — APPROVED** [review]
