### PR TITLE
fix(ios): fixed TabBarItem update for iOS 18+

### LINKED ISSUE #14145: iOS 18 set tab's badge
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

On SDK 12.5.1.GA and iOS 18 / iPadOS 18, if you set the badge value of a Tab, it works only the fist time.

### Expected Behavior

The tab must always show the correct badge  (for example: tab.badge = '7' --> the badge must show '7', also if it's not the first time i've set it)

### Actual behavior

The tab badge is updated only the first time

### Reproducible sample
```js
// create a tabGroup and a tab called "myTab"
var window = Ti.UI.createWindow({
    title: 'My Tab'
});
var myTab = Ti.UI.createTab({
    window: window,
    title: 'My Tab',
    icon: 'myicon.png'
});

// add myTab to the tabGroup
tabGroup.addTab(myTab);

// change tab's badge value
myTab.badge = '5';
myTab.badge = '7';  // tab badge remains '5'

// ATTENTION: I've found this workaround: if you modify (for example) the title of the tab, it works (the tab is refreshed?):

myTab.badge = '5';
myTab.badge = '7';  
var tmp = myTab.title;
myTab.title = tmp + ' ';
myTab.title = tmp;  // now the tab is refreshed and the badge shows '7'
```

### Steps to reproduce

Create an app with a Tab Group.
In a tab, set the badge value more than one time.
See the reproducible sample.

### Platform

iOS

### SDK version you are using

12.5.1.GA

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by hbugdoll**
Fixes #14145.

**Introduction:**
- in `(void)updateTabBarItem` a new `UITabBarItem` is created and assigned to the ViewController with each property update
- iOS 18/iPadOS 18 handles internally the tab bar in a slight different way and iPadOS 18 has also introduced a new "floating" tab bar
- it turned out that under iPadOS 18+ it is necessary to use the "original" `UITabBarItem` to update the badge value

**Description:**
- set `tabBarItem` on **correct** ViewController (NavigationController `controller` instead of RootViewController `rootController`)
  - so fixed the error `Inconsistency in UITabBar items and view controllers detected.`
- **reuse** `controller.tabBarItem` when updating the properties (e.g. badge) of a tab bar item
  - needed for updating badge in "floating" tab bar under iPadOS 18+
  - no re-init every `(void)updateTabBarItem` call
  - re-init only in the case of switching to a system item (with system icon) and vice versa
- BTW fixed a memory leak related to `UITabBarAppearance`
- aligned call sequence for tab bar items with system icons and custom icons 
- added some comments for better clarity

### CODE REVIEW

**Comment by m1ga** [comment]
Tested it on iPhone and iPad and both badges are set correctly now :+1:

**Comment by m1ga** [comment]
In another Alloy project I see some issues:

* I use `$.tab_setting.icon = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,"icon_profil.png").read();` to assign generated icons to the tabs in the open event and I don't see the icons.
* when I click on a tab it will crash with
```
[ERROR] Application received error: Inconsistency in UITabBar items and view controllers detected. No view controller matches the UITabBarItem '<UITabBarItem: 0x102f8a7d0> title='Pläne' selected'.
[ERROR]     0   CoreFoundation                      0x00000001804f39e8 __exceptionPreprocess + 172
[ERROR]     1   libobjc.A.dylib                     0x000000018009c084 objc_exception_throw + 72
[ERROR]     2   Foundation                          0x00000001810353c0 _userInfoForFileAndLine + 0
[ERROR]     3   UIKitCore                           0x00000001859c10c0 -[UITabBarController _viewControllerForTabBarItem:] + 388
[ERROR]     4   UIKitCore                           0x00000001859c1164 -[UITabBarController _tabBarDidChangeSelectionToItem:] + 28
[ERROR]     5   UIKitCore                           0x00000001857bdf90 -[UITabBar _didSelectButtonForItem:] + 308
[ERROR]     6   UIKitCore                           0x00000001852e0c78 block_destroy_helper.30 + 43056
[ERROR]     7   UIKitCore                           0x00000001851aea08 __swift_memcpy9_8 + 8720
[ERROR]     8   UIKitCore                           0x00000001861b0fcc -[UIAction performWithSender:target:] + 104
[ERROR]     9   UIKitCore                           0x0000000185ae7e6c -[UIControl _sendActionsForEvents:withEvent:] + 284
[ERROR]     10  UIKitCore                           0x00000001852d87e4 block_destroy_helper.30 + 9116
[ERROR]     11  UIKitCore                           0x00000001852e0924 block_destroy_helper.30 + 42204
[ERROR]     12  UIKitCore                           0x0000000185d408ec -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 76
[ERROR]     13  UIKitCore                           0x0000000185d499ec _UIGestureRecognizerSendTargetActions + 88
[ERROR]     14  UIKitCore                           0x0000000185d46760 _UIGestureRecognizerSendActions + 296
[ERROR]     15  UIKitCore                           0x0000000185d46324 -[UIGestureRecognizer _updateGestureForActiveEvents] + 320
[ERROR]     16  UIKitCore                           0x0000000185d4af30 -[UIGestureRecognizer gestureNode:didUpdatePhase:] + 296
[ERROR]     17  Gestures                            0x000000022efbf64c GFGestureNodeDefaultValue + 4468
[ERROR]     18  Gestures                            0x000000022efdc858 _swift_stdlib_malloc_size + 26304
[ERROR]     19  Gestures                            0x000000022f0070ac __swift_memcpy24_8 + 20672
[ERROR]     20  Gestures                            0x000000022f02e90c GFGestureNodeCoordinatorCreate + 2148
[ERROR]     21  UIKitCore                           0x0000000185d37e18 -[UIGestureEnvironment _updateForEvent:window:] + 468
[ERROR]     22  UIKitCore                           0x000000018629b3d4 -[UIWindow sendEvent:] + 2796
[ERROR]     23  UIKitCore                           0x0000000186279714 -[UIApplication sendEvent:] + 376
[ERROR]     24  Fitness Plan                        0x00000001021f3cd8 -[TiUIApplication sendEvent:] + 404
[ERROR]     25  UIKitCore                           0x000000018630dc6c __dispatchPreprocessedEventFromEventQueue + 1184
[ERROR]     26  UIKitCore                           0x0000000186310920 __processEventQueue + 4800
[ERROR]     27  UIKitCore                           0x0000000186308ecc updateCycleEntry + 168
[ERROR]     28  UIKitCore                           0x0000000185773878 _UIUpdateSequenceRunNext + 120
[ERROR]     29  UIKitCore                           0x000000018617ec90 schedulerStepScheduledMainSectionContinue + 56
[ERROR]     30  UpdateCycle                         0x00000002509462b4 _ZN2UC10DriverCore18continueProcessingEv + 80
[ERROR]     31  CoreFoundation                      0x00000001804114ac __CFMachPortPerform + 164
[ERROR]     32  CoreFoundation                      0x000000018044dbe0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
[ERROR]     33  CoreFoundation                      0x000000018044d1f8 __CFRunLoopDoSource1 + 480
[ERROR]     34  CoreFoundation                      0x000000018044c2c0 __CFRunLoopRun + 2100
[ERROR]     35  CoreFoundation                      0x0000000180446e24 _CFRunLoopRunSpecificWithOptions + 496
[ERROR]     36  GraphicsServices                    0x00000001925319bc GSEventRunModal + 116
[ERROR]     37  UIKitCore                           0x000000018625fc3c -[UIApplication _run] + 772
[ERROR]     38  UIKitCore                           0x0000000186263e64 UIApplicationMain + 124
[ERROR]     39  Fitness Plan                        0x00000001021845b0 main + 884
[ERROR]     40  dyld                                0x00000001029293d0 start_sim + 20
[ERROR]     41  ???                                 0x0000000102a64d54 0x0 + 4339420500
[ERROR] libc++abi: terminating due to uncaught exception of type NSException
```


13.0.0:



13.1.0:

**Comment by hbugdoll** [comment]
@m1ga Thanks for testing and reporting 👍 
I can now reproduce the issue and I'am working on it.

**Comment by hbugdoll** [comment]
@m1ga The new issue could be reproduced by modifying your example from https://github.com/tidev/titanium-sdk/issues/14145#issuecomment-3422338133 as follows
```
var win1 = Ti.UI.createWindow({
    backgroundColor: 'blue',
    title: 'Blue'
});
win1.add(Ti.UI.createLabel({text: 'I am a blue window.'}));

var win2 = Ti.UI.createWindow({
    backgroundColor: 'red',
    title: 'Red'
});
win2.add(Ti.UI.createLabel({text: 'I am a red window.'}));

var tab1 = Ti.UI.createTab({
    window: win1,
    title: 'Blue',
    badge: 10
}),
tab2 = Ti.UI.createTab({
    window: win2,
    title: 'Red'
}),
tabGroup = Ti.UI.createTabGroup({
    tabs: [tab1, tab2]
});
tabGroup.open();

setTimeout(function(){
    tab1.icon = '/assets/images/tab1.png';
    tab2.icon = '/assets/images/tab2.png';
    tab2.badge=2;
}, 2000);
```

which initially leads to `[[UITabBarItem alloc] initWithTitle:title image:nil selectedImage:nil]` in `updateTabBarItem`. Actually, and so far, no problem &ndash; the tab bar items are created without icons and the icons will be set later.

~~But iOS 18 has a modified caching mechanism for the tab bar, which leads to these strange problems...
It appears that tab bar items with icons are handled differently than icon-less tab bar items.
Adding an icon at a later time, apparently a new tab bar item is created internally and then no longer doesn't match its view controller.~~

~~Using an "empty" placeholder image at creation time has solved this problem.~~ see below

**Comment by m1ga** [comment]
It's not crashing anymore but please check the "Red" (2nd tab) title in your example: it's at the wrong position at first and then jumps into place when the timeout is running



In my app it looks like this when I start the app:

and after I clicked on all items it's correct:

**Comment by hbugdoll** [comment]
> It's not crashing anymore but please check the "Red" (2nd tab) title in your example: it's at the wrong position at first and then jumps into place when the timeout is running

Weird behavior on iOS 26!

~~Forcing a relayout of the TabBar is needed. I put it in `didChangeTraitCollection:`, so the relayouting isn't performed unnecessarily often and unnecessarily too early, when the TabBar is still being built up.~~ see below

Bildschirmfoto 2025-11-01 um 21 37 55

----
The result of the example above is as follows.

iOS 26:
Bildschirmfoto 2025-11-01 um 21 38 51
iPadOS 26:
Bildschirmfoto 2025-11-01 um 21 39 29

**Comment by m1ga** [comment]
Thank you for the update :+1: Now it looks fine here too.

**Comment by hbugdoll** [comment]
> Thank you for the update 👍 Now it looks fine here too.

Thanks for checking again.

File: iphone/Classes/TiUITabProxy.m [hunk 1]
```diff
@@ -76,6 +76,7 @@ - (void)_configure
 - (void)didChangeTraitCollection:(NSNotification *)info
 {
   [self updateTabBarItem];
+  [self forceTabBarRelayout];
```
Comment (hansemannn) [inline iphone/Classes/TiUITabProxy.m]: I have to say that I don't like this solution, as it forces additional relayouts on the main thread and uses memory-heavy operations (`UIGraphicsBeginImageContextWithOptions` etc.), just to amend tab badges.

Therefore, there must be an easier / more isolated fix, likely using the lifecycle delegates of the UITabBar / UITabBarController. Can you check in that direction if possible? Also looping in @janvennemann who knows the delegates very well.

**Review by hansemannn — CHANGES_REQUESTED** [review]

File: iphone/Classes/TiUITabProxy.m (hunk 1 above)
Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m]: Thanks for following up!

After a long debugging session I've found "the easier fix" which requires neither a TabBar relayout nor a placeholder image 😃
The TabBarItem has always been set on the wrong ViewController (`rootController` instead of NavigationController `controller`).

**Comment by hbugdoll** [comment]
The updated fix requires neither a TabBar relayout nor a placeholder image.

The TabBarItem has always been set on the wrong ViewController (`rootController` instead of NavigationController `controller`). That causes the `Inconsistency in UITabBar items and view controllers detected` error.

----
Here some own debug logs for the example above...

Setting TabBarItem on the RootViewController `[rootController setTabBarItem:tabBarItem]`:
```
[INFO]  RootViewController: <TiViewController: 0x100f11ef0>
[INFO]  RootViewController's TabBarItem: <UITabBarItem: 0x100f07330> title='Blue' image=<UIImage:0x6000030181b0 anonymous {30, 30} renderingMode=alwaysTemplate>
[INFO]  TabBarController's ViewControllers (1):
[INFO]  - [0] VC: <UINavigationController: 0x13c811e00> | item=<UITabBarItem: 0x100f07330> title='Blue' image=<UIImage:0x6000030181b0 anonymous {30, 30} renderingMode=alwaysTemplate>
[INFO]  TabBarController's TabBarItems (1):
[INFO]  - [0] Item: title="Blue", image=(null)
```

Setting TabBarItem on the NavigationController `[controller setTabBarItem:tabBarItem]`
```
[INFO]  RootViewController: <TiViewController: 0x103946e10>
[INFO]  RootViewController's TabBarItem: <UITabBarItem: 0x103949fc0> title='Blue'
[INFO]  TabBarController's ViewControllers (1):
[INFO]  - [0] VC: <UINavigationController: 0x104039e00> | item=<UITabBarItem: 0x103949e70> title='Blue' image=<UIImage:0x600003028120 anonymous {30, 30} renderingMode=alwaysTemplate> selected
[INFO]  TabBarController's TabBarItems (1):
[INFO]  - [0] Item: title="Blue", image=<UIImage:0x600003028120 anonymous {30, 30} renderingMode=alwaysTemplate>

```

File: iphone/Classes/TiUITabProxy.m [hunk 2]
```diff
@@ -553,30 +553,33 @@ - (void)updateTabBarItem
...
 
+    // badge
     if (badgeColor != nil) {
-      [newItem setBadgeColor:[[TiUtils colorValue:badgeColor] color]];
+      [tabBarItem setBadgeColor:[[TiUtils colorValue:badgeColor] color]];
     }
+    [tabBarItem setBadgeValue:badgeValue];
 
-    [rootController setTabBarItem:newItem];
-    [newItem release];
```
Comment (hansemannn) [inline iphone/Classes/TiUITabProxy.m:573]: No `release` necessary anymore? Check the profiler to be sure

File: iphone/Classes/TiUITabProxy.m [hunk 3]
```diff
@@ -635,12 +638,18 @@ - (void)updateTabBarItem
...
-  ourItem = [[[UITabBarItem alloc] initWithTitle:title image:image selectedImage:activeImage] autorelease];
+  // tab bar item (re-)init
+  if (tabBarItem == nil || systemTab == YES) {
+    tabBarItem = [[UITabBarItem alloc] initWithTitle:title image:image selectedImage:activeImage];
+    [controller setTabBarItem:tabBarItem];
+  } else {
+    [tabBarItem setTitle:title];
+    [tabBarItem setImage:image];
+    [tabBarItem setSelectedImage:activeImage];
+  }
```
Comment (hansemannn) [inline iphone/Classes/TiUITabProxy.m]: Why is all of this necessary to fix a badge? Just trying to understand it better - you will know this part better already.

Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m]: Good point.

`(void)updateTabBarItem` is designed so that a TabBarItem is updated completely in one go.
A call of `Ti.UI.createTab()` results in multiple runs of `(void)updateTabBarItem` depending on the number of properties.
To avoid the many calls to `[[UITabBarItem alloc] initWith...]` and thus memory allocations, I re-use the existing `UITabBarItem`. And I find it completely unnecessary to allocate and initialize a new `UITabBarItem` just to update e.g. the badge value.

I've generalized the PR title and updated the PR description as it's affected to more TabBarItem properties.

File: iphone/Classes/TiUITabProxy.m (hunk 2 above)
Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m:573]: - `ourItem` is renamed to `tabBarItem` and `ourItem` ~~wasn't released explicitly until now~~ ahh, was autoreleased
- `newItem` was only used in the system-icon branch, `tabBarItem` is now also used there

I'll have to check that again...

Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m:573]: You're right.
I reverted to MRC in the system-icon branch and use of `newItem` plus reverted to `autorelease` in the custom-icon branch.

BTW I fixed a memory leak related to `UITabBarAppearance`:
We've overseen, that `UITabBarAppearance.new` equals to `[[UITabBarAppearance alloc] init]` and needed to be released.

File: iphone/Classes/TiUITabProxy.m (hunk 3 above)
Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m]: But the main reason for reusing is indeed badge value updating under iPadOS 18+.
(I tested it unsuccessfully with the correct ViewController, but without reuse of TabBarItem.)

File: iphone/Classes/TiUITabProxy.m (hunk 1 above)
Comment (hansemannn) [reply iphone/Classes/TiUITabProxy.m]: Good that I've mentioned it :-) Looks much better now.

File: iphone/Classes/TiUITabProxy.m [hunk 4]
```diff
@@ -635,12 +645,22 @@ - (void)updateTabBarItem
...
 
-  systemTab = NO;
-  ourItem = [[[UITabBarItem alloc] initWithTitle:title image:image selectedImage:activeImage] autorelease];
+  UITabBarItem *tabBarItem = [controller tabBarItem];
+  if (tabBarItem == nil || systemTab == YES) {
+    // init tab bar item
+    UITabBarItem *newItem = [[[UITabBarItem alloc] initWithTitle:title image:image selectedImage:activeImage] autorelease];
+    [controller setTabBarItem:newItem];
 
+    tabBarItem = [controller tabBarItem];
```
Comment (hansemannn) [inline iphone/Classes/TiUITabProxy.m:655]: Does this need to be released / auto-released?

Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m:655]: The getter of this VC property does not retain the object again.
We don't become owner of `tabBarItem` (no `alloc`, `new`, `copy`, `mutableCopy`, or `retain`).

And `newItem` is autoreleased.

File: iphone/Classes/TiUITabProxy.m (hunk 1 above)
Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m]: Yes, definitely!

File: iphone/Classes/TiUITabProxy.m (hunk 4 above)
Comment (hbugdoll) [reply iphone/Classes/TiUITabProxy.m:655]: @hansemannn Do you agree with this?

**Review by hansemannn — APPROVED** [review]
Great work!

**Comment by hbugdoll** [comment]
@hansemannn Thanks for merging!
