### PR TITLE
fix: (iOS) Fix app freezing when trying to hide & show popover repeatedly and popover layout issues

### LINKED ISSUE #13915: Popover has glitch UI in iPadOS 17 and makes app freezing
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Popover has glitch UI in iOS 17 something like padding (top, bottom padding if arrow Up or down || left, right padding if arrow left  or right) and makes app freezing when trying to open and hide it repeatedly, you will think that's not right way to open and close it repeatedly but in real project i have a lot of buttons which open a popover so when click on one of it and close to open another that will show glitch UI or makes app freezing.

### For first time
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 35

### After closing and opening
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 26

### App freezing in opening popover
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 05

### Reproducible sample

```
var popover;

const win = Ti.UI.createWindow();

const hidePopover = Ti.UI.createButton({
	title: 'Hide Popover',
	backgroundColor: 'orange',
	width: 160,
	height: 40
});
hidePopover.addEventListener("click", (e) => {
	popover.hide();
});

const showPopover = Ti.UI.createButton({
	title: "Show Popover",
	backgroundColor: 'red',
	width: 120,
	height: 40
});

showPopover.addEventListener("click", (e) => {
	const popoverWin = Ti.UI.createWindow({
		backgroundColor: 'red',
		title: 'Popover Window',
		rightNavButton: hidePopover
	});

	const listView = Ti.UI.createListView({
		backgroundColor: 'blue',
	});
	const sections = [];

	const fruitDataSet = [
		{ properties: { title: 'Apple' } },
		{ properties: { title: 'Banana' } },
	];
	const fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits', items: fruitDataSet });
	sections.push(fruitSection);

	const vegDataSet = [
		{ properties: { title: 'Carrots' } },
		{ properties: { title: 'Potatoes' } },
	];
	const vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables', items: vegDataSet });
	sections.push(vegSection);

	listView.sections = sections;

	popoverWin.add(listView);

	const fishDataSet = [
		{ properties: { title: 'Cod' } },
		{ properties: { title: 'Haddock' } },
	];
	const fishSection = Ti.UI.createListSection({ headerTitle: 'Fish', items: fishDataSet });
	listView.appendSection(fishSection);

	const popoverNav = Ti.UI.createNavigationWindow({
		window: popoverWin
	});

	popover = Ti.UI.iPad.createPopover({
		contentView: popoverNav
	});

	popover.show({ view: showPopover });
});

win.add(showPopover);

win.open();
```

### Steps to reproduce

1. create new classic app
2. add this sample code
3. click on showPopover button to show it
4. then click on hidePopover or outside the window
5. try to do this repeatedly

### Platform

iOS

### SDK version you are using

12.2.0

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by AhmedMSayed**
Fixes [13915](https://github.com/tidev/titanium-sdk/issues/13915)

**Sample**

```var popover;

const win = Ti.UI.createWindow();

const hidePopover = Ti.UI.createButton({
	title: 'Hide Popover',
	backgroundColor: 'orange',
	width: 160,
	height: 40
});
hidePopover.addEventListener("click", (e) => {
	popover.hide();
});

const showPopover = Ti.UI.createButton({
	title: "Show Popover",
	backgroundColor: 'red',
	width: 120,
	height: 40
});

showPopover.addEventListener("click", (e) => {
	const popoverWin = Ti.UI.createWindow({
		backgroundColor: 'red',
		title: 'Popover Window',
		rightNavButton: hidePopover
	});

	const listView = Ti.UI.createListView({
		backgroundColor: 'blue',
	});
	const sections = [];

	const fruitDataSet = [
		{ properties: { title: 'Apple' } },
		{ properties: { title: 'Banana' } },
	];
	const fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits', items: fruitDataSet });
	sections.push(fruitSection);

	const vegDataSet = [
		{ properties: { title: 'Carrots' } },
		{ properties: { title: 'Potatoes' } },
	];
	const vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables', items: vegDataSet });
	sections.push(vegSection);

	listView.sections = sections;

	popoverWin.add(listView);

	const fishDataSet = [
		{ properties: { title: 'Cod' } },
		{ properties: { title: 'Haddock' } },
	];
	const fishSection = Ti.UI.createListSection({ headerTitle: 'Fish', items: fishDataSet });
	listView.appendSection(fishSection);

	const popoverNav = Ti.UI.createNavigationWindow({
		window: popoverWin
	});

	popover = Ti.UI.iPad.createPopover({
		contentView: popoverNav
	});

	popover.show({ view: showPopover });
});

win.add(showPopover);

win.open();

### CODE REVIEW

File: iphone/Classes/TiUIiPadPopoverProxy.m [hunk 1]
```diff
@@ -405,6 +359,11 @@ - (void)proxyDidRelayout:(id)sender
   }
 }
 
+- (UIModalPresentationStyle)adaptivePresentationStyleForPresentationController:(UIPresentationController *)controller
+{
+  return UIModalPresentationNone;
```
Comment (hansemannn) [inline iphone/Classes/TiUIiPadPopoverProxy.m:364]: Does this need to be hardcoded?

File: iphone/Classes/TiUIiPadPopoverProxy.m [hunk 2]
```diff
@@ -466,13 +427,9 @@ - (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(N
...
     NSValue *insetsValue = [NSValue valueWithUIEdgeInsets:newInsets];
 
-    if (!UIEdgeInsetsEqualToEdgeInsets(oldInsets, newInsets)) {
+    if (!UIEdgeInsetsEqualToEdgeInsets(oldInsets, newInsets) || deviceRotated) {
       deviceRotated = NO;
       [self updateContentViewWithSafeAreaInsets:insetsValue];
-    } else if (deviceRotated) {
-      // [self viewController]  need a bit of time to set its frame while rotating
-      deviceRotated = NO;
-      [self performSelector:@selector(updateContentViewWithSafeAreaInsets:) withObject:insetsValue afterDelay:.05];
```
Comment (hansemannn) [inline iphone/Classes/TiUIiPadPopoverProxy.m:475]: Does the safe area still update correctly after rotation?

File: iphone/Classes/TiUIiPadPopoverProxy.m [hunk 3]
```diff
@@ -388,7 +342,7 @@ - (void)updateContentViewWithSafeAreaInsets:(NSValue *)insetsValue
         UIEdgeInsets edgeInsets = [insetsValue UIEdgeInsetsValue];
         viewController.view.frame = CGRectMake(viewController.view.frame.origin.x + edgeInsets.left, viewController.view.frame.origin.y + edgeInsets.top, viewController.view.frame.size.width - edgeInsets.left - edgeInsets.right, viewController.view.frame.size.height - edgeInsets.top - edgeInsets.bottom);
       },
-      NO);
+      YES);
```
Comment (hansemannn) [inline iphone/Classes/TiUIiPadPopoverProxy.m:345]: This will cause the main thread to block, is this intended?

File: iphone/Classes/TiUIiPadPopoverProxy.m [hunk 4]
```diff
@@ -259,47 +266,13 @@ - (void)cleanup
   [viewController.view removeObserver:self forKeyPath:@"safeAreaInsets"];
   RELEASE_TO_NIL(viewController);
   RELEASE_TO_NIL(popoverView);
-  [self performSelector:@selector(release) withObject:nil afterDelay:0.5];
+  [self release];
```
Comment (hansemannn) [inline iphone/Classes/TiUIiPadPopoverProxy.m:269]: The old statement was probably added ages ago, but I hope it's not causing further issues now.

**Review by hansemannn — CHANGES_REQUESTED** [review]
Some quick questions, but nothing blocking.

File: iphone/Classes/TiUIiPadPopoverProxy.m (hunk 1 above)
Comment (AhmedMSayed) [reply iphone/Classes/TiUIiPadPopoverProxy.m:364]: YES, UIModalPresentationNone tells the presentation controller to use the original presentation style which in our case will display a popover.

File: iphone/Classes/TiUIiPadPopoverProxy.m (hunk 3 above)
Comment (AhmedMSayed) [reply iphone/Classes/TiUIiPadPopoverProxy.m:345]: Yes, This will fix layout issue when you open popover from barButtonItem

File: iphone/Classes/TiUIiPadPopoverProxy.m (hunk 2 above)
Comment (AhmedMSayed) [reply iphone/Classes/TiUIiPadPopoverProxy.m:475]: Yes, I deleted the delay and makes updateContentViewWithSafeAreaInsets to waiting for main thread
So I ensured safe area update correctly, This will fix layout issue when you open popover from barButtonItem

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@AhmedMSayed Can you please sign the CLA? Then we're good to go! @cb1kenobi what's the website again? 😇

**Comment by AhmedMSayed** [comment]
> @AhmedMSayed Can you please sign the CLA? Then we're good to go! @cb1kenobi what's the website again? 😇

Sure just tell me how

**Comment by hansemannn** [comment]
@AhmedMSayed @joshualambert This is the last blocker for the 12.2.1. If you folks can handle the CLA today, we can release the version 😊

**Comment by AhmedMSayed** [comment]
@hansemannn I see new issue when presenting popover from modal window
I fixed it by present popover from topPresentedController, I tested it again and it works

**Comment by hansemannn** [comment]
Now only the CLA is pending and then we can merge and release 12.2.1!

**Comment by AhmedMSayed** [comment]
Already talked to Josh and signed in docusign, didn't know what i can do next

**Comment by cb1kenobi** [comment]
I pinged Josh. He needs to verify it's been signed and update https://github.com/tidev/organization-docs/blob/main/AUTHORIZED_CONTRIBUTORS.md.

**Comment by cb1kenobi** [comment]
Awesome, thanks @AhmedMSayed!
